package br.ufrn.info.bpm.smb;

public enum TarefaSolicitacao {
	SOLICITAR_MATERIAL, ANALISE_DO_COORDENADOR, ANALISE_DO_SETOR_DE_COMPRAS,
	FLUXO_DE_COMPRAS, FLUXO_DE_TOMBAMENTO, RECEBIMENTO_DO_BEM;
	//SUBMETEU_PROCESSO, CHEFIA_EMITIU_PARECER, AVALIADOR_EMITIU_PARECER, PARECER_ASSINADO
}
