package br.ufrn.info.bpm.smb;

public enum TarefaSolicitacao {
	SOLICITAR_MATERIAL_ALUNO, SOLICITAR_MATERIAL_COORDENADOR, ANALISE_DO_COORDENADOR, ANALISE_DO_SETOR_DE_COMPRAS,
	FLUXO_DE_COMPRAS, FLUXO_DE_TOMBAMENTO, RECEBIMENTO_DO_BEM;
}
